import path from "node:path";
import { fileURLToPath } from "node:url";
import { readFile } from "node:fs/promises";
import { describe, expect, test } from "vitest";

import { runNode, writeTempTspFile } from "../test-utils.js";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");

function distCliPath(): string {
  return path.join(repoRoot, "dist", "cli.js");
}

const peopleSchema = `
  using coco;

  @coco.connection({
    contentCategory: "people",
    graphApiVersion: "beta",
    name: "People connector",
    connectionId: "peopleconnector",
    connectionDescription: "People connector generated by cocogen"
  })
  @coco.profileSource({
    webUrl: "https://example.com/people",
    displayName: "Example People Directory"
  })
  @coco.item()
  model PersonProfile {
    @coco.id
    @coco.label("personAccount")
    @coco.source("upn", "userPrincipalName")
    userPrincipalName: string;

    @coco.label("personProjects")
    @coco.source("project", "displayName")
    @coco.source("client", "client.displayName")
    projects: string[];
  }
`;

describe("people graph types (e2e)", () => {
  test("generates complex types with properties in TS output", async () => {
    const entry = await writeTempTspFile(peopleSchema);
    const outDir = path.join(path.dirname(entry), "out-people-ts");

    const init = await runNode([
      distCliPath(),
      "generate",
      "--lang",
      "ts",
      "--tsp",
      entry,
      "--out",
      outDir,
      "--use-preview-features",
    ], {
      cwd: repoRoot,
      env: { NO_COLOR: "1", CI: "1" },
    });

    expect(init.code).toBe(0);

    const peopleTs = await readFile(path.join(outDir, "src", "core", "people.ts"), "utf8");
    expect(peopleTs).toContain("export type CompanyDetail = {");
    expect(peopleTs).toContain("displayName?: string | null;");
    expect(peopleTs).toContain("address?: PhysicalAddress | null;");
  });

  test("generates complex types with properties in dotnet output", async () => {
    const entry = await writeTempTspFile(peopleSchema);
    const outDir = path.join(path.dirname(entry), "out-people-dotnet");

    const init = await runNode([
      distCliPath(),
      "generate",
      "--lang",
      "dotnet",
      "--tsp",
      entry,
      "--out",
      outDir,
      "--use-preview-features",
    ], {
      cwd: repoRoot,
      env: { NO_COLOR: "1", CI: "1" },
    });

    expect(init.code).toBe(0);

    const payload = await readFile(path.join(outDir, "Core", "PeoplePayload.cs"), "utf8");
    expect(payload).toContain("public sealed class CompanyDetail");
    expect(payload).toContain("public string? DisplayName { get; init; }");
    expect(payload).toContain("public PhysicalAddress? Address { get; init; }");
  });
});
