import { describe, expect, test } from "vitest";
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";

import { initStarterTsp } from "../../src/tsp/init-tsp.js";
import { writeTempDir } from "../test-utils.js";

describe("initStarterTsp", () => {
  test("creates a content starter file with .tsp extension", async () => {
    const dir = await writeTempDir();
    const result = await initStarterTsp({
      outPath: path.join(dir, "schema"),
      kind: "content",
      prompt: false,
    });

    expect(result.outPath.endsWith(".tsp")).toBe(true);
    const contents = await readFile(result.outPath, "utf8");
    expect(contents).toContain("using coco;");
    expect(contents).toContain("@coco.connection({");
    expect(contents).toContain("@coco.item()");
    expect(contents).toContain("model Item");
    expect(contents).toContain("@coco.id");

    const packageJson = await readFile(path.join(dir, "package.json"), "utf8");
    expect(packageJson).toContain("@wictorwilen/cocogen");

    const tspConfig = await readFile(path.join(dir, "tspconfig.yaml"), "utf8");
    expect(tspConfig).toContain("@wictorwilen/cocogen");

    const agents = await readFile(path.join(dir, "AGENTS.md"), "utf8");
    expect(agents).toContain("How to write a schema");
    expect(agents).toContain("npx cocogen validate --tsp schema.tsp");
    expect(agents).toContain("Validation (cocogen validate)");
  });

  test("creates a people starter file", async () => {
    const dir = await writeTempDir();
    const result = await initStarterTsp({
      outPath: path.join(dir, "people-schema.tsp"),
      kind: "people",
      modelName: "Profile",
      idPropertyName: "upn",
    });

    const contents = await readFile(result.outPath, "utf8");
    expect(contents).toContain("contentCategory: \"people\"");
    expect(contents).toContain("name: \"People connector\"");
    expect(contents).toContain("connectionId: \"peopleconnector\"");
    expect(contents).toContain("connectionDescription: \"People connector generated by cocogen\"");
    expect(contents).toContain("model Profile");
    expect(contents).toContain("@coco.source(\"UPN\", \"userPrincipalName\")");
    expect(contents).toContain("account: string;");

    const agents = await readFile(path.join(dir, "AGENTS.md"), "utf8");
    expect(agents).toContain("People connectors (preview)");
    expect(agents).toContain("--use-preview-features");
    expect(agents).toContain("Microsoft Graph **/beta**");
  });

  test("fails when file exists and force is false", async () => {
    const dir = await writeTempDir();
    const outPath = path.join(dir, "schema.tsp");
    await writeFile(outPath, "existing", "utf8");

    await expect(
      initStarterTsp({
        outPath,
        kind: "content",
        force: false,
      })
    ).rejects.toThrow(/already exists/i);
  });

  test("overwrites when force is true", async () => {
    const dir = await writeTempDir();
    const outPath = path.join(dir, "schema.tsp");
    await writeFile(outPath, "existing", "utf8");

    const result = await initStarterTsp({
      outPath,
      kind: "content",
      modelName: "CustomItem",
      idPropertyName: "customId",
      force: true,
    });

    const contents = await readFile(result.outPath, "utf8");
    expect(contents).toContain("model CustomItem");
    expect(contents).toContain("customId: string;");
  });

  test("rejects prompt when not in TTY", async () => {
    const originalTty = process.stdin.isTTY;
    Object.defineProperty(process.stdin, "isTTY", { value: false, configurable: true });

    await expect(initStarterTsp({ prompt: true })).rejects.toThrow(/Prompt requires an interactive TTY/i);

    Object.defineProperty(process.stdin, "isTTY", { value: originalTty, configurable: true });
  });
});
